<?php

/**
 * @file
 * Contains hook implementations for entity_access_password module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\entity_access_password\Service\PasswordAccessManagerInterface;

/**
 * Implements hook_theme().
 */
function entity_access_password_theme(): array {
  return [
    'entity_access_password_form' => [
      'variables' => [
        'help_text' => '',
        'hint' => '',
        'form' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function entity_access_password_entity_view_mode_alter(string &$view_mode, EntityInterface $entity) : void {
  // Quick return to avoid instantiation.
  if ($view_mode == PasswordAccessManagerInterface::PROTECTED_VIEW_MODE) {
    return;
  }

  /** @var \Drupal\entity_access_password\Service\PasswordAccessManagerInterface $password_access_manager */
  $password_access_manager = \Drupal::service('entity_access_password.password_access_manager');
  if ($password_access_manager->isEntityViewModeProtected($view_mode, $entity) && !$password_access_manager->hasUserAccessToEntity($entity)) {
    $view_mode = PasswordAccessManagerInterface::PROTECTED_VIEW_MODE;
  }
}
