entity_access_password.settings:
  type: config_object
  label: Settings
  mapping:
    global_password:
      type: string
      label: 'Global hashed password'
    random_password_length:
      type: integer
      label: 'Random password length'

# Field instance.
field.field_settings.entity_access_password_password:
  type: mapping
  label: 'Password Protection field settings'
  mapping:
    password_entity:
      type: boolean
      label: 'Per entity password access check'
    password_bundle:
      type: boolean
      label: 'Bundle password access check'
    password_global:
      type: boolean
      label: 'Global password access check'
    password:
      type: string
      label: 'Password'
    view_modes:
      type: sequence
      label: 'View modes'
      sequence:
        type: string
        label: 'View mode ID'

# Default value.
field.value.entity_access_password_password:
  type: mapping
  label: 'Default value'
  mapping:
    is_protected:
      type: boolean
      label: 'Protect Entity'
    show_title:
      type: boolean
      label: 'Show Title'
    hint:
      type: text
      label: 'Hint'
    password:
      type: string
      label: 'Password'

# Field widget.
field.widget.settings.entity_access_password_password:
  type: mapping
  label: 'Default widget settings'
  mapping:
    open:
      type: boolean
      label: 'Show widget details as opened by default'
    show_entity_title:
      type: string
      label: 'Show entity title'
    show_hint:
      type: string
      label: 'Show hint'
    allow_random_password:
      type: boolean
      label: 'Allow random password'

# Field formatter.
field.formatter.settings.entity_access_password_form:
  type: mapping
  label: 'Password form formatter'
  mapping:
    help_text:
      type: text
      label: 'Help text'
