<?php

/**
 * @file
 * Install and update functions for the module.
 */

declare(strict_types = 1);

use Drupal\entity_access_password_user_data_backend\Service\UserDataBackendInterface;

/**
 * Implements hook_uninstall().
 */
function entity_access_password_user_data_backend_uninstall(bool $is_syncing) : void {
  /** @var \Drupal\user\UserDataInterface $user_data */
  $user_data = \Drupal::service('user.data');
  $user_data->delete(UserDataBackendInterface::MODULE_NAME);
}
