<?php

/**
 * @file
 * Contains hook implementations for the module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\entity_access_password_user_data_backend\HookHandler\EntityTypeInfo;

/**
 * Implements hook_entity_operation().
 */
function entity_access_password_user_data_backend_entity_operation(EntityInterface $entity) : array {
  /** @var \Drupal\entity_access_password_user_data_backend\HookHandler\EntityTypeInfo $instance */
  $instance = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EntityTypeInfo::class);
  return $instance->entityOperation($entity);
}
